# Generated by Django 6.0.7 on 2026-07-21 22:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon (panier)'), ('confirmee', 'Confirmée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=16)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('formation_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='accounts.formationsanitaire')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'unique_together': {('commande', 'produit')},
            },
        ),
    ]
