# Generated by Django 6.0.7 on 2026-07-21 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money')], default='orange_money', max_length=32)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué')], default='en_attente', max_length=16)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('date_initiation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_initiation'],
            },
        ),
    ]
