# Generated by Django 6.0.7 on 2026-07-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('especes', 'Espèces (cash)')], default='orange_money', max_length=32),
        ),
    ]
