# Generated by Django 6.0.7 on 2026-08-22 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_paiement_date_maj_paiement_paiement_maj_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('especes', 'Espèces (cash)')], default='orange_money', max_length=32),
        ),
        migrations.CreateModel(
            name='ReglementPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('especes', 'Espèces (cash)')], default='especes', max_length=32)),
                ('date_reglement', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements', to='paiements.paiement')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ['date_reglement'],
            },
        ),
    ]
