# Generated by Django 6.0.7 on 2026-08-31 01:05

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def _reprendre_la_date_de_saisie(apps, schema_editor):
    """Les règlements déjà en base n'ont pas de date de paiement saisie : la meilleure
    approximation connue est leur horodatage de saisie. Sans cela, le `default` leur
    attribuerait la date du jour de la migration et fausserait tout l'historique."""
    Reglement = apps.get_model("paiements", "ReglementPaiement")
    for r in Reglement.objects.all().iterator():
        r.date_paiement = timezone.localtime(r.date_reglement).date()
        r.save(update_fields=["date_paiement"])


def _revenir_en_arriere(apps, schema_editor):
    """Rien à défaire : le champ disparaît avec le rollback du schéma."""


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_backfill_reglements_historiques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglementpaiement',
            options={'ordering': ['date_paiement', 'date_reglement'], 'verbose_name': 'Règlement', 'verbose_name_plural': 'Règlements'},
        ),
        migrations.AddField(
            model_name='reglementpaiement',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date à laquelle la FOSA a réellement réglé, qui peut précéder la saisie.'),
        ),
        migrations.RunPython(_reprendre_la_date_de_saisie, _revenir_en_arriere),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('especes', 'Espèces (cash)'), ('virement_bancaire', 'Virement bancaire')], default='orange_money', max_length=32),
        ),
        migrations.AlterField(
            model_name='reglementpaiement',
            name='date_reglement',
            field=models.DateTimeField(auto_now_add=True, help_text="Horodatage de la saisie dans l'application."),
        ),
        migrations.AlterField(
            model_name='reglementpaiement',
            name='methode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('especes', 'Espèces (cash)'), ('virement_bancaire', 'Virement bancaire')], default='especes', max_length=32),
        ),
    ]
