# Generated by Django 6.0.7 on 2026-07-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sage', models.CharField(help_text='Code produit dans Sage Gescom', max_length=64, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('unite', models.CharField(blank=True, help_text='Ex: boîte, flacon, comprimé', max_length=32)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True, help_text='Désactivé automatiquement si absent du dernier import')),
                ('derniere_synchro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
    ]
