# Generated by Django 6.0.7 on 2026-07-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='magasin',
            field=models.CharField(choices=[('principal', 'Magasin principal'), ('ucpc', 'Magasin UCPC'), ('autre', 'Autre magasin (non affiché dans le catalogue)')], default='principal', help_text='Seuls les produits des magasins Principal et UCPC apparaissent dans le catalogue FOSA', max_length=16),
        ),
    ]
