# Generated by Django 6.0.7 on 2026-08-22 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_produit_magasin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, help_text='Emoji affiché à côté du nom du rayon', max_length=8)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rayon',
                'verbose_name_plural': 'Rayons',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalogue.rayon'),
        ),
    ]
