"""
Django settings for frps_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-^e1u$db^r-+3r#9t7pb11pi@%nzpmtt71(w(p!2k4q=(d1o5ng")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
    'catalogue',
    'commandes',
    'notifications',
    'paiements',
    'stock_sync',
    'statistiques',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'frps_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notifications_non_lues',
            ],
        },
    },
]

WSGI_APPLICATION = 'frps_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# En dev : SQLite par défaut. En prod : définir DATABASE_URL dans le .env,
# ex: postgres://user:password@localhost:5432/frps_commande

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

# Affiche tous les nombres avec un separateur de milliers (espace en fr-fr) dans
# les templates, ex. 1 000 000 au lieu de 1000000.
USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'catalogue:liste'
LOGOUT_REDIRECT_URL = 'login'


# --- Intégrations externes (voir .env.example) ---

STOCK_CONNECTOR_BACKEND = env("STOCK_CONNECTOR_BACKEND", default="mock")
SQLSERVER_HOST = env("SQLSERVER_HOST", default="")
SQLSERVER_DB = env("SQLSERVER_DB", default="")
SQLSERVER_USER = env("SQLSERVER_USER", default="")
SQLSERVER_PASSWORD = env("SQLSERVER_PASSWORD", default="")
SQLSERVER_DRIVER = env("SQLSERVER_DRIVER", default="ODBC Driver 17 for SQL Server")

SMS_BACKEND = env("SMS_BACKEND", default="log")
SMS_API_URL = env("SMS_API_URL", default="")
SMS_API_KEY = env("SMS_API_KEY", default="")

# --- Orange Developer (SMS API) : meilleure délivrabilité vers les numéros Orange Cameroun ---
ORANGE_SMS_CLIENT_ID = env("ORANGE_SMS_CLIENT_ID", default="")
ORANGE_SMS_CLIENT_SECRET = env("ORANGE_SMS_CLIENT_SECRET", default="")
ORANGE_SMS_SENDER_ADDRESS = env("ORANGE_SMS_SENDER_ADDRESS", default="")
# Nom affiché comme expéditeur (ex: "SMS 844926" par défaut chez Orange, ou "FRPSNO"
# une fois le sender name personnalisé validé par Orange). Optionnel.
ORANGE_SMS_SENDER_NAME = env("ORANGE_SMS_SENDER_NAME", default="")

# --- MTN Developer (produit "SMS V2") : meilleure délivrabilité vers les numéros MTN Cameroun ---
MTN_SMS_CLIENT_ID = env("MTN_SMS_CLIENT_ID", default="")
MTN_SMS_CLIENT_SECRET = env("MTN_SMS_CLIENT_SECRET", default="")
MTN_SMS_SENDER_ADDRESS = env("MTN_SMS_SENDER_ADDRESS", default="")

PAYMENT_GATEWAY = env("PAYMENT_GATEWAY", default="mock")
ORANGE_MONEY_API_URL = env("ORANGE_MONEY_API_URL", default="")
ORANGE_MONEY_MERCHANT_KEY = env("ORANGE_MONEY_MERCHANT_KEY", default="")
ORANGE_MONEY_COMPTE_FRPS = env("ORANGE_MONEY_COMPTE_FRPS", default="+237 6XX XXX XXX (FRPS - à confirmer)")

WHATSAPP_BACKEND = env("WHATSAPP_BACKEND", default="log")
WHATSAPP_API_URL = env("WHATSAPP_API_URL", default="")
WHATSAPP_API_TOKEN = env("WHATSAPP_API_TOKEN", default="")
WHATSAPP_NOTIFICATION_NUMBERS = env.list("WHATSAPP_NOTIFICATION_NUMBERS", default=[])

# URL publique HTTPS du serveur (tunnel ngrok en dev, domaine réel en prod) : nécessaire
# pour que Twilio puisse télécharger le PDF de la commande via une media_url publique.
PUBLIC_BASE_URL = env("PUBLIC_BASE_URL", default="http://localhost:8000")

TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN", default="")
TWILIO_WHATSAPP_FROM = env("TWILIO_WHATSAPP_FROM", default="whatsapp:+14155238886")
TWILIO_SMS_FROM = env("TWILIO_SMS_FROM", default="")

# --- Notifications push (Web Push) ---
# Identité du serveur pour les navigateurs/services de push (FCM sur Android).
# Clé privée stockée avec des \n échappés (une seule ligne dans .env / Render) ;
# `.replace` la reconvertit en PEM valide.
VAPID_PUBLIC_KEY = env("VAPID_PUBLIC_KEY", default="")
VAPID_PRIVATE_KEY = env("VAPID_PRIVATE_KEY", default="").replace("\\n", "\n")
VAPID_CLAIMS_EMAIL = env("VAPID_CLAIMS_EMAIL", default="mailto:contact@frpsno.com")

# --- Email (rapports périodiques) ---
# "console" par défaut (imprime l'email dans les logs, aucun envoi réel — pratique en
# local/dev) ; passer à "smtp" avec les identifiants d'un fournisseur (ex: Brevo,
# smtp-relay.brevo.com:587) pour un envoi réel.
EMAIL_BACKEND_MODE = env("EMAIL_BACKEND_MODE", default="console")
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_BACKEND_MODE == "smtp"
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = env("EMAIL_HOST", default="smtp-relay.brevo.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="rapports@frpsno.com")


# --- Sécurité production ---
# Le tunnel Cloudflare termine le HTTPS et transmet en HTTP en interne : Django doit
# faire confiance à l'en-tête X-Forwarded-Proto pour savoir que la requête est bien HTTPS.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ("localhost", "127.0.0.1")]
