# Generated by Django 6.0.7 on 2026-07-21 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('type_evenement', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('paiement_confirme', 'Paiement confirmé')], max_length=32)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], max_length=16)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('detail_erreur', models.TextField(blank=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_envoyes', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'SMS envoyé',
                'verbose_name_plural': 'SMS envoyés',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
