# Generated by Django 6.0.7 on 2026-07-21 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=20)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], max_length=16)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('detail_erreur', models.TextField(blank=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_envoyes', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Envoi WhatsApp',
                'verbose_name_plural': 'Envois WhatsApp',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
