# Generated by Django 6.0.7 on 2026-07-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('notifications', '0002_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_cible', models.CharField(help_text='Rôle destinataire (accounts.Role)', max_length=32)),
                ('type_evenement', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('paiement_confirme', 'Paiement confirmé')], max_length=32)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_internes', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Notification interne',
                'verbose_name_plural': 'Notifications internes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
