# Generated by Django 6.0.7 on 2026-08-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='date_statut_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='reference_externe',
            field=models.CharField(blank=True, help_text='resource_id (Orange) ou SID (Twilio) renvoyé par la passerelle', max_length=100),
        ),
        migrations.AddField(
            model_name='smslog',
            name='statut_livraison',
            field=models.CharField(blank=True, help_text='Statut brut reçu du callback DR (ex: DeliveredToTerminal, DeliveryImpossible)', max_length=32),
        ),
    ]
