# Generated by Django 6.0.7 on 2026-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pushsubscription_appareil_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='date_dernier_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='dernier_statut',
            field=models.CharField(blank=True, help_text="Réponse du service de push au dernier envoi. « envoyé » signifie accepté, pas livré : c'est le test depuis l'appareil qui tranche.", max_length=32),
        ),
    ]
