# Generated by Django 6.0.7 on 2026-08-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('notifications', '0007_trace_envoi_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('type_evenement', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('paiement_confirme', 'Paiement confirmé')], max_length=32)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], max_length=16)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('detail_erreur', models.TextField(blank=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_envoyes', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Email envoyé',
                'verbose_name_plural': 'Emails envoyés',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
